spring.application.name=KinalApp1

#Conexion MySQL
Spring.datasource.url=jdbc:mysql://Localhost:3306/dbKinal_App_in5av?createDatabaseIfNotExist=true
Spring.datasource.username=root
Spring.datasource.password=admin

server.port=8081

#JPA / hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

